name: nonrad continuous integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up PDM
      uses: pdm-project/setup-pdm@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: True
    - name: Install dependencies
      run: |
        pdm install -dG lint,test
    - name: Lint with ruff
      run: |
        pdm run ruff check nonrad
    - name: Lint with mypy
      run: |
        pdm run mypy nonrad
    - name: Test with pytest
      run: |
        pdm run pytest nonrad
